#-------------------------------
# General Site Settings
baseURL = "https://www.lookingforwisdom.com/"
languageCode = "en-us"
title = "Looking for Wisdom"
paginate = 6
enableRobotsTXT = true

[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Philosophy for the insatiably curious: insights and ideas from the world's philosophical traditions, from the ancient world to the present day."
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.
  header = "Looking for Wisdom"
  copyright = "Will Buckingham"
  languageCode = "en-GB"
  author = "Will Buckingham"

[taxonomies]
  tag = 'tags'

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "latest"
    name = "Latest"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 4

  [[menu.main]]
      name = "Search"
      url = "/search/"
      weight = 5    

 [[menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 6


      # Footer Menu
      [[menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

      [[menu.footer]]
      identifier = "latest"
      name = "Latest"
      url = "/posts/"
      weight = 2

      [[menu.footer]]
      identifier = "projects"
      name = "Projects"
      url = "/projects/"
      weight = 3

      [[menu.footer]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 4

      [[menu.footer]]
      name = "Search"
      url = "/search/"
      weight = 5

      [[menu.footer]]
      identifier = "privacy"
      name = "Privacy"
      url = "/privacy/"
      weight = 6

      [[menu.footer]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 7



  #-------------------------------

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/lookingforwisdom"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com/groups/lookingforwisdom"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com/wiselooking"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Looking for Wisdom"
    hero__description = "Philosophy for the insatiably curious."
    hero__image = "/images/LFW-header.jpg"


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Get updates" # Add your button text


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects__title= "Projects & Books"
    projects__description= "Find out about some of the things we are up to!"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = false
    testimonial__title = "What are people saying?"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Aspen Carder"
    image = "https://via.placeholder.com/200x200"
    designation = "Lettering Artist"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Lydia Siphron"
    image = "https://via.placeholder.com/200x200"
    designation = "Designer"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Craig Vaccaro"
    image = "https://via.placeholder.com/200x200"
    designation = "Web developer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Anika Calzoni"
    image = "https://via.placeholder.com/200x200"
    designation = "Lettering Artist"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Marcus Botosh"
    image = "https://via.placeholder.com/200x200"
    designation = "Full Stack Designer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Latest Updates"
    blog__description = "Latest updates from Looking for Wisdom"


  #-------------------------------
  # Gallery Footer Settings
  [params.gallery]
    enable = false

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x800"

  [[params.gallery_image]]
    image_alt = "Lifestyle"
    image_url = "https://via.placeholder.com/800x800"

  [[params.gallery_image]]
    image_alt = "Hobby"
    image_url = "https://via.placeholder.com/800x800"

  [[params.gallery_image]]
    image_alt = "Notes"
    image_url = "https://via.placeholder.com/800x800"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "contact@lookingforwisdom.com" # Add your form_id


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false


#-------------------------------
# Permalinks
[permalinks]
posts = "/:slug/"