[build]
  command = "npm install && hugo --minify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.98.0"


[functions]
  node_bundler = "esbuild"

# This will redirect all sub-pages to an equivalent page on WillBuckingham.com
[[redirects]]
  from = "https://www.lookingforwisdom.com/*"
  to = "https://www.willbuckingham.com/:splat"
  status = 301
  force = true

# This will redirect all sub-pages to an equivalent page on WillBuckingham.com
[[redirects]]
  from = "https://lookingforwisdom.com/*"
  to = "https://www.willbuckingham.com/:splat"
  status = 301
  force = true

# This will redirect all sub-pages to an equivalent page on WillBuckingham.com
[[redirects]]
  from = "http://www.lookingforwisdom.com/*"
  to = "https://www.willbuckingham.com/:splat"
  status = 301
  force = true

# This will redirect all sub-pages to an equivalent page on WillBuckingham.com
[[redirects]]
  from = "http://lookingforwisdom.com/*"
  to = "https://www.willbuckingham.com/:splat"
  status = 301
  force = true

# This will redirect the home page to WillBuckingham.com
[[redirects]]
  from = "https://www.lookingforwisdom.com/"
  to = "https://www.willbuckingham.com/"
  status = 301
  force = true